### ISSUE TITLE
Problems with usage 

### ISSUE THREAD

**Issue by rng64** [PoonLab/MiCall-Lite#20]
Following the instructions of the README for uncompressed FASTQs leads to the following error.

```python
rng64@Arsibalt: ~/git/micall$ python2 run-sample.py -u SRR1577734_1.fastq SRR1577734_2.fastq

usage: run-sample.py [-h] [--fastq1 FASTQ1] [--fastq2 FASTQ2]
                     [--outdir OUTDIR] [--unzipped] [--interop INTEROP]
                     [--readlen READLEN] [--index INDEX]
run-sample.py: error: unrecognized arguments: SRR1577734_1.fastq SRR1577734_2.fastq
```
Providing the file path for the fastq files yields a different error.

```python
rng64@Arsibalt:~/git/micall$ python2 run-sample.py -u --fastq1 /data/fq/SRR1577734_1.fastq --fastq2 /data/fq/SRR1577734_2.fastq
Traceback (most recent call last):
  File "run-sample.py", line 69, in <module>
    main()
  File "run-sample.py", line 41, in main
    args = parseArgs()
  File "run-sample.py", line 36, in parseArgs
    args.outdir = os.path.dirname(args.fastq1)
  File "/usr/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'file' object has no attribute 'rfind'

**Comment by ArtPoon** [comment]
Ok, pull `master` branch and re-install.

**Comment by ArtPoon** [comment]
@rng64 have you reproduced this problem with current `master`?

**Comment by rng64** [comment]
@ArtPoon I have not have this problem with the current `master`

**Comment by ArtPoon** [comment]
Thanks, closing
