### ISSUE TITLE
gotoh2 not found after installation

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/MiCall-Lite#21]
```
Traceback (most recent call last):
  File "run-sample.py", line 11, in <module>
    from micall.core.remap import remap
  File "/home/rng64/git/micall/micall/core/remap.py", line 23, in <module>
    from micall.alignment.gotoh2 import Aligner
  File "/home/rng64/git/micall/micall/alignment/gotoh2.py", line 1, in <module>
    from micall.alignment import _gotoh2
ImportError: cannot import name '_gotoh2'
```

**Comment by ArtPoon** [comment]
Reproduced on orolo

**Comment by ArtPoon** [comment]
Install log from Kestrel:
```console
art@Kestrel:~/git/micall$ sudo python3 setup.py install
running install
running build
running build_py
package init file 'micall/__init__.py' not found (or not a regular file)
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/micall
creating build/lib.linux-x86_64-3.5/micall/core
copying micall/core/censor_fastq.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/project_config.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/miseq_logging.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/parse_interop.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/__init__.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/prelim_map.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/aln2counts.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/filter_quality.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/remap.py -> build/lib.linux-x86_64-3.5/micall/core
copying micall/core/sam2aln.py -> build/lib.linux-x86_64-3.5/micall/core
creating build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/reference_distances.py -> build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/externals.py -> build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/__init__.py -> build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/dd.py -> build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/sample_sheet_parser.py -> build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/sample_fastq.py -> build/lib.linux-x86_64-3.5/micall/utils
copying micall/utils/translation.py -> build/lib.linux-x86_64-3.5/micall/utils
creating build/lib.linux-x86_64-3.5/micall/alignment
copying micall/alignment/__init__.py -> build/lib.linux-x86_64-3.5/micall/alignment
copying micall/alignment/gotoh2.py -> build/lib.linux-x86_64-3.5/micall/alignment
copying micall/projects.json -> build/lib.linux-x86_64-3.5/micall
creating build/lib.linux-x86_64-3.5/micall/alignment/models
copying micall/alignment/models/HYPHY_NUC.csv -> build/lib.linux-x86_64-3.5/micall/alignment/models
copying micall/alignment/models/Biopp.csv -> build/lib.linux-x86_64-3.5/micall/alignment/models
copying micall/alignment/models/NWALIGN.csv -> build/lib.linux-x86_64-3.5/micall/alignment/models
copying micall/alignment/models/EmpHIV25.csv -> build/lib.linux-x86_64-3.5/micall/alignment/models
package init file 'micall/__init__.py' not found (or not a regular file)
running build_ext
building 'micall.alignment._gotoh2' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/micall
creating build/temp.linux-x86_64-3.5/micall/alignment
creating build/temp.linux-x86_64-3.5/micall/alignment/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c micall/alignment/src/_gotoh2.c -o build/temp.linux-x86_64-3.5/micall/alignment/src/_gotoh2.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/micall/alignment/src/_gotoh2.o -o build/lib.linux-x86_64-3.5/micall/alignment/_gotoh2.cpython-35m-x86_64-linux-gnu.so
running install_lib
creating /usr/local/lib/python3.5/dist-packages/micall
creating /usr/local/lib/python3.5/dist-packages/micall/alignment
creating /usr/local/lib/python3.5/dist-packages/micall/alignment/models
copying build/lib.linux-x86_64-3.5/micall/alignment/models/HYPHY_NUC.csv -> /usr/local/lib/python3.5/dist-packages/micall/alignment/models
copying build/lib.linux-x86_64-3.5/micall/alignment/models/Biopp.csv -> /usr/local/lib/python3.5/dist-packages/micall/alignment/models
copying build/lib.linux-x86_64-3.5/micall/alignment/models/NWALIGN.csv -> /usr/local/lib/python3.5/dist-packages/micall/alignment/models
copying build/lib.linux-x86_64-3.5/micall/alignment/models/EmpHIV25.csv -> /usr/local/lib/python3.5/dist-packages/micall/alignment/models
copying build/lib.linux-x86_64-3.5/micall/alignment/__init__.py -> /usr/local/lib/python3.5/dist-packages/micall/alignment
copying build/lib.linux-x86_64-3.5/micall/alignment/_gotoh2.cpython-35m-x86_64-linux-gnu.so -> /usr/local/lib/python3.5/dist-packages/micall/alignment
copying build/lib.linux-x86_64-3.5/micall/alignment/gotoh2.py -> /usr/local/lib/python3.5/dist-packages/micall/alignment
creating /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/censor_fastq.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/project_config.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/miseq_logging.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/parse_interop.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/__init__.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/prelim_map.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/aln2counts.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/filter_quality.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/remap.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/core/sam2aln.py -> /usr/local/lib/python3.5/dist-packages/micall/core
copying build/lib.linux-x86_64-3.5/micall/projects.json -> /usr/local/lib/python3.5/dist-packages/micall
creating /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/reference_distances.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/externals.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/__init__.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/dd.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/sample_sheet_parser.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/sample_fastq.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
copying build/lib.linux-x86_64-3.5/micall/utils/translation.py -> /usr/local/lib/python3.5/dist-packages/micall/utils
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/alignment/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/alignment/gotoh2.py to gotoh2.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/censor_fastq.py to censor_fastq.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/project_config.py to project_config.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/miseq_logging.py to miseq_logging.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/parse_interop.py to parse_interop.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/prelim_map.py to prelim_map.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/aln2counts.py to aln2counts.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/filter_quality.py to filter_quality.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/remap.py to remap.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/core/sam2aln.py to sam2aln.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/reference_distances.py to reference_distances.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/externals.py to externals.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/dd.py to dd.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/sample_sheet_parser.py to sample_sheet_parser.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/sample_fastq.py to sample_fastq.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/micall/utils/translation.py to translation.cpython-35.pyc
running install_egg_info
Writing /usr/local/lib/python3.5/dist-packages/MiCall-0.0.0.egg-info
```
