### ISSUE TITLE
Error when --threads flag is used

### ISSUE THREAD

**Issue by dfornika** [PoonLab/MiCall-Lite#33]
Running `micall` with the `--threads` flag produces this error:

```
[dfornika@sabin hcv_micall_testing]$ micall --threads 8 input/HCV300_1.fastq.gz input/HCV300_2.fastq.gz --outdir outdir
Using /home/dfornika/miniconda3/envs/micall-lite-gitub/bin/bowtie2 version 2.2.8
MiCall-Lite running sample HCV300_1...
  Preliminary map
  Iterative remap
Traceback (most recent call last):
  File "/home/dfornika/miniconda3/envs/micall-lite-gitub/bin/micall", line 248, in <module>
    run_sample(args)
  File "/home/dfornika/miniconda3/envs/micall-lite-gitub/bin/micall", line 163, in run_sample
    keep=args.keep
  File "/home/dfornika/miniconda3/envs/micall-lite-gitub/lib/python3.5/site-packages/micall/core/remap.py", line 441, in remap
    worker_pool = multiprocessing.Pool(processes=nthreads) if nthreads > 1 else None
TypeError: unorderable types: str() > int()
```

Running on the same sample without specifying `--threads` results in no error:

```
[dfornika@sabin hcv_micall_testing]$ micall input/HCV300_1.fastq.gz input/HCV300_2.fastq.gz --outdir outdir
Using /home/dfornika/miniconda3/envs/micall-lite-gitub/bin/bowtie2 version 2.2.8
MiCall-Lite running sample HCV300_1...
  Preliminary map
  Iterative remap
  Generating alignment file
  Generating count files
```

Input fastq files are from this sample:

https://www.ebi.ac.uk/ena/data/view/SAMN11126538

**Comment by ArtPoon** [comment]
Whooops.  Forgot to cast the argument.  Gimme a sec.

**Comment by ArtPoon** [comment]
Ok @dfornika please pull from `master` and try again.

**Comment by dfornika** [comment]
Fixed. Thanks!
