### ISSUE TITLE
Deprecated function 'itertools.imap'

### ISSUE THREAD

**Issue by dfornika** [PoonLab/MiCall-Lite#37]
I'm getting the following error when running micall-lite v0.1rc2 on python 3.7:

```
Traceback (most recent call last):
  File "/home/dfornika/miniconda3/envs/__micall-lite@0.1rc2/bin/micall", line 248, in <module>
    run_sample(args)
  File "/home/dfornika/miniconda3/envs/__micall-lite@0.1rc2/bin/micall", line 163, in run_sample
    keep=args.keep
  File "/home/dfornika/miniconda3/envs/__micall-lite@0.1rc2/lib/python3.7/site-packages/micall/core/remap.py", line 526, in remap
    conseqs = build_conseqs(samfile, seeds=seeds, worker_pool=worker_pool)
  File "/home/dfornika/miniconda3/envs/__micall-lite@0.1rc2/lib/python3.7/site-packages/micall/core/remap.py", line 363, in build_conseqs
    distance_report=distance_report)
  File "/home/dfornika/miniconda3/envs/__micall-lite@0.1rc2/lib/python3.7/site-packages/micall/core/remap.py", line 178, in sam_to_conseqs
    merged_reads = itertools.imap(
AttributeError: module 'itertools' has no attribute 'imap'
```

It seems that the `imap` function was removed from `itertools`, but the built-in `map()` function can be used in its place.

https://stackoverflow.com/a/30271758

**Comment by ArtPoon** [comment]
Thanks for catching this error.  I'll investigate.

**Comment by dfornika** [comment]
@ArtPoon thanks for merging. Would you be able to pin a new release soon to these bugfixes can be pushed to the bioconda package?

**Comment by ArtPoon** [comment]
> @ArtPoon thanks for merging. Would you be able to pin a new release soon to these bugfixes can be pushed to the bioconda package?

done
